apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: po4awtb25-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: po4awtb25-nodejs 
  name: po4awtb25-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: po4awtb25-nodejs 
